name: .NET

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]
  workflow_dispatch:
defaults:
  run:
    working-directory: "./src/TailBlazor.Toast"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies      
      run: dotnet restore --disable-parallel --ignore-failed-sources
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5  
      with:
        PROJECT_FILE_PATH:  src/TailBlazor.Toast/TailBlazor.Toast.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
